### ISSUE TITLE
Draft releases messed up

### ISSUE THREAD

**Issue by cantino** [cantino/mcfly#391]
@praveenperera it looks like each package is going into a different draft release now, I don't think due to any change on our part. Have you seen this before? https://github.com/cantino/mcfly/releases

**Comment by suzuki-shunsuke** [comment]
v0.8.4 doesn't have pre-built binaries for linux.

https://github.com/cantino/mcfly/releases/tag/v0.8.4

<img width="444" alt="image" src="https://github.com/cantino/mcfly/assets/13323303/ab9fbb93-e89f-41ce-af5c-53ebcfcce2a7">

It seems builds succeeded.

https://github.com/cantino/mcfly/actions/runs/7317302030/job/19932679935

```
Run actions/upload-release-asset@v1
  with:
    upload_url: https://uploads.github.com/repos/cantino/mcfly/releases/135022051/assets{?name,label}
    asset_path: mcfly.tar.gz
    asset_name: mcfly-v0.8.4-aarch64-unknown-linux-gnu.tar.gz
    asset_content_type: application/gzip
  env:
    BIN: mcfly
    GITHUB_TOKEN: ***
```

Is this issue related? Or different issue?
